### ISSUE TITLE
No way to use the library in test_driver dir

### ISSUE THREAD

**Issue by Ameterezu** [google/reflectable.dart#216]
Hello!

I would like to use reflection for my ui tests in dir test_driver. I found, that it's impossible, because defaults don't include this dir:
defaultGenerateFor: const _i3.InputSet(include: [
        'benchmark/**.dart',
        'bin/**.dart',
        'example/**.dart',
        'lib/main.dart',
        'test/**.dart',
        'tool/**.dart',
        'web/**.dart'
      ]
Please tell me how can I get around this limitation?

**Comment by maxime-aubry** [comment]
You can add a build.yaml file :

```
targets:
  $default:
    builders:
      reflectable:
        generate_for:
          - test/*_test.dart
        options:
          formatted: true
```

BUT, there is a bug with reflectable. You can't build your app if you have multiple files.
It's my case with [https://github.com/google/reflectable.dart/issues/213](https://github.com/google/reflectable.dart/issues/213).

Maybe i could use "part" command to merge all my files...
